# Generated by Django 3.2.12 on 2022-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='professor_firstname',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name of Professor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='professor_lastname',
            field=models.CharField(max_length=30, null=True, verbose_name='Lastname of Professor'),
        ),
    ]
