# Generated by Django 3.2.12 on 2022-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220225_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='professors',
            field=models.ManyToManyField(blank=True, to='events.Professor'),
        ),
    ]
