# Generated by Django 3.2.12 on 2022-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220225_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='professor_firstname',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='professor_lastname',
        ),
        migrations.AddField(
            model_name='professor',
            name='identifier',
            field=models.CharField(max_length=30, null=True, verbose_name='Identifier of Professor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='professor_identifier',
            field=models.CharField(max_length=30, null=True, verbose_name='Identifier of Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='firstname',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name of Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='lastname',
            field=models.CharField(max_length=30, null=True, verbose_name='Lastname of Professor'),
        ),
    ]
