# Generated by Django 3.2.12 on 2022-02-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220226_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
