# Generated by Django 3.2.12 on 2022-02-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_professor_ratings_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='identifier',
            new_name='professor_id',
        ),
    ]
