# Generated by Django 3.2.12 on 2022-03-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220226_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='code',
            new_name='module_code',
        ),
    ]
