# Generated by Django 3.2.12 on 2022-03-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_code_module_module_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='module_code',
            new_name='module',
        ),
    ]
